### ISSUE TITLE
Add support for the new 9.00 JB

### ISSUE THREAD

**Issue by debuti** [CelliesProjects/ESP8266-ps4-jailbreak#1]
It would be awesome to have support for the 9.00 jailbreak with an esp8266

**Comment by CelliesProjects** [comment]
Hi debuti.
There will be a version for 9.00.

No ETA though. My PS4 is still on 7.55

**Comment by CelliesProjects** [comment]
@debuti I am working on a new version for esp8266. ETA is a couple of days.
You will need an esp8266 with at least 8MB flash memory.

**Comment by CelliesProjects** [comment]
The new version has gone live at https://github.com/CelliesProjects/ps4_jb900_esp8266
